export const ADMIN_FETCH_REQUEST = 'ADMIN_FETCH_REQUEST'
export const ADMIN_FETCH_SUCCESS = 'ADMIN_FETCH_SUCCESS'
export const ADMIN_FETCH_FAIL = 'ADMIN_FETCH_FAIL'
export const ADMIN_FETCH_RESET = 'ADMIN_FETCH_RESET'

export const ADMIN_ADD_REQUEST = 'ADMIN_ADD_REQUEST'
export const ADMIN_ADD_SUCCESS = 'ADMIN_ADD_SUCCESS'
export const ADMIN_ADD_FAIL = 'ADMIN_ADD_FAIL'
export const ADMIN_ADD_RESET = 'ADMIN_ADD_RESET'
