export const EMPLOYEE_SIGNIN_REQUEST = 'EMPLOYEE_SIGNIN_REQUEST'
export const EMPLOYEE_SIGNIN_SUCCESS = 'EMPLOYEE_SIGNIN_SUCCESS'
export const EMPLOYEE_SIGNIN_FAIL = 'EMPLOYEE_SIGNIN_FAIL'
export const EMPLOYEE_SIGNOUT = 'EMPLOYEE_SIGNOUT'

export const EMPLOYEE_SIGNUP_REQUEST = 'EMPLOYEE_SIGNUP_REQUEST'
export const EMPLOYEE_SIGNUP_SUCCESS = 'EMPLOYEE_SIGNUP_SUCCESS'
export const EMPLOYEE_SIGNUP_FAIL = 'EMPLOYEE_SIGNUP_FAIL'


export const EMPLOYEE_FETCH_REQUEST = 'EMPLOYEE_FETCH_REQUEST'
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS'
export const EMPLOYEE_FETCH_FAIL = 'EMPLOYEE_FETCH_FAIL'
export const EMPLOYEE_FETCH_RESET = 'EMPLOYEE_FETCH_RESET'

export const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST'
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS'
export const EMPLOYEE_ADD_FAIL = 'EMPLOYEE_ADD_FAIL'
export const EMPLOYEE_ADD_RESET = 'EMPLOYEE_ADD_RESET'